- hosts: localhost
  vars_prompt:
    - name: mfa_code
      private: false
  tasks:
    - sts_assume_role:
        role_arn: "{{ full_access_role_arn }}"
        role_session_name: "ansible-test.yaml"
        duration_seconds: 900
        region: "{{ aws_region }}"
        mfa_serial_number: "{{ mfa_token_arn }}"
        mfa_token: "{{ mfa_code }}"
        aws_access_key: "{{ vault_aws_access_key }}"
        aws_secret_key: "{{ vault_aws_secret_key }}"
      register: assumed_role
    - name: "Setup Temporary Credentials"
      set_fact:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
