---
- import_playbook: obtain_session_token.yaml

- hosts: aws_iam_user
  gather_facts: False
  roles:
    - iam_user

- hosts: docsender_lambda
  gather_facts: False
  roles:
    - role: lambda
      handler: "ocoen.docsender.handle_event"
      runtime: "python3.6"
      zip_file: "../docsender/dist/lambda-ocoen_docsender-0.1.0.zip"

- hosts: pdf_store_bucket
  gather_facts: False
  roles:
    - role: s3_bucket
      iam_access:
        - user: docsigner_user
          key_patterns:
            "templates/*": read
            "results/*": write
        - user: test_user
          key_patterns:
            "*": read_write

- hosts: transaction_signing_queue
  gather_facts: False
  roles:
    - role: sqs_queue
      iam_access:
        - user: docsigner_user
          mode: dequeue
        - user: test_user
          mode: enqueue

- hosts: signing_events_topic
  gather_facts: False
  roles:
    - role: sns_topic
      iam_access:
        - user: docsigner_user
          mode: send
        - user: test_user
          mode: subscribe
      subscriptions:
        - endpoint: "{{ hostvars['docsender_lambda'].resource_arn }}"
          lambda_name: docsender_lambda
          protocol: lambda

- hosts: test_users
  gather_facts: False
  roles:
    - role: aws_services_ini
      dest_dir: "{{ playbook_dir }}/test-data/creds/{{ inventory_dir|basename }}"
      file_name: "{{ inventory_hostname }}-aws_services.ini"
      iam_user: "{{ inventory_hostname }}"
      queues:
        transaction_queue: transaction_signing_queue
      buckets:
        pdf_bucket: pdf_store_bucket
      topics:
        signing_events_topic: signing_events_topic
