---
- hosts: localhost
  tasks:
    - name: "Transaction Signing Queue"
      sqs_queue:
        name: "{{ env_prefix }}-transaction-signing-queue"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: transaction_signing_queue_info
    - name: "inventory/aws-transaction_signing_queue"
      template:
        src: templates/inventory/sqs_queue.j2
        dest: "{{ inventory_dir }}/aws-transaction_signing_queue"
      with_items:
        - name: transaction_signing_queue
          registration: "{{ transaction_signing_queue_info }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "PDF Store Bucket"
      s3_bucket:
        name: "{{ item.name }}"
        state: present
        policy: "{{ lookup('template', 'templates/s3_policy/encrypted_bucket.json.j2') }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: pdf_store_bucket_info_list
      with_items:
        - name: "{{ env_prefix | lower }}-pdf-store-{{ env_ulid | lower }}"
    - name: "PDF Store Bucket Info"
      set_fact:
        pdf_store_bucket_info: "{{ pdf_store_bucket_info_list.results[0] }}"
    - name: "inventory/aws-pdf_store_bucket"
      template:
        src: templates/inventory/s3_bucket.j2
        dest: "{{ inventory_dir }}/aws-pdf_store_bucket"
      with_items:
        - name: pdf_store_bucket
          registration: "{{ pdf_store_bucket_info }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "Docsigner User"
      iam:
        iam_type: user
        name: "{{ env_prefix }}-docsigner"
        access_key_state: create
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: docsigner_user_info
    - name: "inventory/aws-docsigner_user"
      template:
        src: templates/inventory/iam_user.j2
        dest: "{{ inventory_dir }}/aws-docsigner_user"
        mode: 0600
      when: docsigner_user_info.changed
      with_items:
        - name: docsigner_user
          registration: "{{ docsigner_user_info }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "Reload Inventory"
      meta: refresh_inventory

- hosts: docsigner_user
  tasks:
    - name: "Transaction Signing Queue Receiver Policy"
      iam_policy:
        iam_type: user
        iam_name: "{{ name }}"
        policy_name: transaction_signing_queue_receiver
        policy_json: "{{ lookup('template', 'templates/iam_policy/sqs_queue_receive.json.j2') }}"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items:
        - "{{ hostvars['transaction_signing_queue'] }}"
      loop_control:
        label: "{{ item.name }}"
    - name: "PDF Store Bucket Access"
      iam_policy:
        iam_type: user
        iam_name: "{{ name }}"
        policy_name: pdf_store_bucket_access
        policy_json: "{{ lookup('template', 'templates/iam_policy/s3_access.json.j2') }}"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items:
        - name: pdf_store_bucket
          arn: "{{ hostvars['pdf_store_bucket'].arn }}"
          key_patterns:
            "templates/*": read
            "results/*": write
      loop_control:
        label: "{{ item.name }}"

- hosts: pdf_store_bucket
  tasks:
    - name: "Ensure Template in Bucket"
      s3:
        bucket: "{{ name }}"
        object: "templates/template.pdf"
        src: "s3-initial-data/template.pdf"
        encrypt: true
        mode: put
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
