---
- hosts: localhost
  tasks:
    - name: "Transaction Signing Queue"
      sqs_queue:
        name: "{{ env_prefix }}-transaction-signing-queue"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: transaction_signing_queue_info
    - name: "inventory/aws-transaction_signing_queue"
      template:
        src: templates/inventory/sqs_queue.j2
        dest: "{{ inventory_dir }}/aws-transaction_signing_queue"
      with_items:
        - name: transaction_signing_queue
          registration: "{{ transaction_signing_queue_info }}"
    - name: "PDF Store Bucket"
      s3_bucket:
        name: "{{ env_prefix | lower }}-pdf-store-{{ env_ulid | lower }}"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: pdf_store_bucket_info
    - name: "inventory/aws-pdf_store_bucket"
      template:
        src: templates/inventory/s3_bucket.j2
        dest: "{{ inventory_dir }}/aws-pdf_store_bucket"
      with_items:
        - name: pdf_store_bucket
          registration: "{{ pdf_store_bucket_info }}"
    - name: "Docsigner User"
      iam:
        iam_type: user
        name: "{{ env_prefix }}-docsigner"
        access_key_state: create
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: docsigner_user_info
    - name: "inventory/aws-docsigner_user"
      template:
        src: templates/inventory/iam_user.j2
        dest: "{{ inventory_dir }}/aws-docsigner_user"
        mode: 0600
      when: docsigner_user_info.changed
      with_items:
        - name: docsigner_user
          registration: "{{ docsigner_user_info }}"
      loop_control:
        label: "{{ item.name }}"
    - set_fact:
        queue_arn: "{{ transaction_signing_queue_info.queue_arn }}"
        queue_name: "{{ transaction_signing_queue_info.name }}"
    - name: "Transaction Signing Queue Receiver Policy"
      iam_policy:
        iam_type: user
        iam_name: "{{ env_prefix }}-docsigner"
        policy_name: transaction_signing_queue_receiver
        policy_json: "{{ lookup('template', 'templates/iam_policy/sqs_queue_receive.json.j2') }}"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items:
        - "{{ transaction_signing_queue_info }}"
    - name: "PDF Store Bucket Access"
      iam_policy:
        iam_type: user
        iam_name: "{{ env_prefix }}-docsigner"
        policy_name: pdf_store_bucket_access
        policy_json: "{{ lookup('template', 'templates/iam_policy/s3_access.json.j2') }}"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items:
        - bucket: "{{ pdf_store_bucket_info.name }}"
          readable_keys:
            - "templates/*"
  handlers:

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Reload Inventory"
      meta: refresh_inventory

- hosts: localhost
  tasks:
    - name: "Ensure Template in Bucket"
      s3:
        bucket: "{{ hostvars['pdf_store_bucket']['name'] }}"
        object: "templates/template.pdf"
        src: "pdf-signer/template.pdf"
        mode: put
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
