---
- hosts: localhost
  gather_facts: False
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "inventory/aws_services"
      template:
        src: templates/inventory/aws_services.j2
        dest: "{{ inventory_dir }}/aws_services"
    - name: "Reload Inventory"
      meta: refresh_inventory

- hosts: aws_service
  gather_facts: False
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "inventory/host_vars/service_name"
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory
    - name: "Determin Region"
      set_fact:
        new_region: "{{ aws_logical_inventory[ aws_type + 's' ][inventory_hostname].region|default(aws_default_region) }}"
    - name: "Check Region Hasn't Changed"
      assert:
        that: region is not defined or region == new_region
        msg: "Canot change region from {{ region|default('null') }} to {{ new_region }}"
    - name: "inventory/host_vars/service_name/aws_service_spec.yaml"
      template:
        src: "templates/inventory/host_vars/{{ aws_type }}_spec.yaml.j2"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aws_service_spec.yaml"
    - name: "Load Service Spec"
      include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aws_service_spec.yaml"
