---
- hosts: localhost
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "inventory/aws_services"
      template:
        src: templates/inventory/aws_services.j2
        dest: "{{ inventory_dir }}/aws_services"
    - name: "Reload Inventory"
      meta: refresh_inventory

- hosts: aws_service
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "inventory/host_vars/service_name"
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory
    - name: "inventory/host_vars/service_name/aws_service_spec.yaml"
      template:
        src: "templates/inventory/host_vars/{{ aws_type }}_spec.yaml.j2"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aws_service_spec.yaml"
    - name: "Load Service Spec"
      include_vars:
        file: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aws_service_spec.yaml"
