---
- import_playbook: obtain_session_token.yaml

- hosts: aws_iam_user
  gather_facts: False
  roles:
    - iam_user

- hosts: transaction_signing_queue
  gather_facts: False
  roles:
    - role: sqs_queue
      iam_access:
        - user: docsigner_user
          mode: dequeue
        - user: test_user
          mode: enqueue

- hosts: signing_events_topic
  gather_facts: False
  roles:
    - role: sns_topic
      iam_access:
        - user: docsigner_user
          mode: send
        - user: test_user
          mode: subscribe

- hosts: pdf_store_bucket
  gather_facts: False
  roles:
    - role: s3_bucket
      iam_access:
        - user: docsigner_user
          key_patterns:
            "templates/*": read
            "results/*": write
        - user: test_user
          key_patterns:
            "*": read_write

- hosts: aws_iam_user:&test_infrastructure
  gather_facts: False
  tasks:
    - include_tasks: includes/aws_services_ini.yaml
      vars:
        dest_dir: "{{ playbook_dir }}/test-data/creds/{{ inventory_dir|basename }}"
        file_name: "{{ inventory_hostname }}-aws_services.ini"
        iam_user: "{{ inventory_hostname }}"
        queues:
          transaction_queue: transaction_signing_queue
        buckets:
          pdf_bucket: pdf_store_bucket
        topics:
          signing_events_topic: signing_events_topic
