---
- hosts: pdf_signer
  tasks:
    - name: "Ensure Docsigner User Exists"
      assert:
        that: "'docsigner_user' in hostvars"
        msg: "docsigner_user not found, have you created the AWS infrastructure?"

    - name: "pdf-signer dependencies"
      pip:
        name:
          - boto3
          - iso8601

    - name: "Copy pdf-signer"
      synchronize:
        mode: push
        src: "pdf-signer/"
        dest: "{{ ansible_user_dir }}/pdf-signer"
        perms: true
        recursive: true
        delete: true
        use_ssh_args: true
      notify: queue_reader_changed

    - name: "Activate Queue Reader Cron"
      cron:
        name: queue-reader.py
        state: present
        minute: "*"
        job: sh -c "pgrep queue-reader.py > /dev/null ||
          AWS_DEFAULT_REGION='{{ hostvars['localhost']['aws_region'] }}'
          AWS_ACCESS_KEY_ID='{{ hostvars['docsigner_user']['aws_access_key'] }}'
          AWS_SECRET_ACCESS_KEY='{{ hostvars['docsigner_user']['aws_secret_key'] }}'
          TRANSACTION_QUEUE_NAME='{{ hostvars['transaction_signing_queue']['name'] }}'
          PDF_BUCKET_NAME='{{ hostvars['pdf_store_bucket']['name'] }}'
          PYTHONUNBUFFERED=true
          {{ ansible_user_dir }}/pdf-signer/queue-reader.py > log.txt 2>&1"
      notify: queue_reader_changed
  handlers:
    - name: "Stop Queue Reader"
      command: pkill queue-reader.py
      register: result
      failed_when: false
      changed_when: "result.rc == 0"
      listen: queue_reader_changed
