---
- hosts: localhost
  tasks:
    - set_fact:
        docsigner_user_name: "{{ hostvars['docsigner_user']['name'] }}"
        transaction_signing_queue_name: "{{ hostvars['transaction_signing_queue']['name'] }}"
    - name: "Transaction Signing Queue Receiver Policy"
      iam_policy:
        iam_type: user
        iam_name: "{{ docsigner_user_name }}"
        policy_name: transaction_signing_queue_receiver
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - name: "Docsigner User"
      iam:
        iam_type: user
        name: "{{ docsigner_user_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - name: "Transaction Signing Queue"
      sqs_queue:
        name: "{{ transaction_signing_queue_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - name: "inventory/transaction_signing_queue"
      file:
        path: "{{ inventory_dir }}/aws-transaction_signing_queue"
        state: absent
    - name: "inventory/docsigner_user"
      file:
        path: "{{ inventory_dir }}/aws-docsigner_user"
        state: absent
