---
- hosts: aws_service
  gather_facts: False
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "inventory/host_vars/service_name"
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: absent

- hosts: localhost
  gather_facts: False
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "inventory/aws_services"
      file:
        path: "{{ inventory_dir }}/aws_services"
        state: absent
