---
- include: includes/obtain_session_token.yaml
- include: includes/aws_creds_host_facts.yaml

- hosts: pdf_signer
  tasks:
    - name: "Deactivate Queue Reader Cron"
      cron:
        name: queue-reader.py
        state: absent
    - name: "Stop Queue Reader"
      command: pkill queue-reader.py
      register: result
      failed_when: false
      changed_when: "result.rc == 0"

- hosts: aws_sns_topic
  tasks:
    - name: "{{ inventory_hostname }}"
      sns_topic:
        name: "{{ name }}"
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"

- hosts: aws_s3_bucket
  tasks:
    - name: "{{ inventory_hostname }}"
      s3_bucket:
        name: "{{ name }}"
        state: absent
        force: true
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"

- hosts: aws_sqs_queue
  tasks:
    - name: "{{ inventory_hostname }}"
      sqs_queue:
        name: "{{ name }}"
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"

- hosts: aws_iam_user
  vars_files:
    - infrastructure.yaml
  tasks:
    - name: "{{ inventory_hostname }}"
      iam:
        iam_type: user
        name: "{{ name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ iam_aws_access_key }}"
        aws_secret_key: "{{ iam_aws_secret_key }}"
        security_token: "{{ iam_security_token|default(omit) }}"
    - name: "inventory/host_vars/aws_user/aws_user_creds.yaml"
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aws_user_creds.yaml"
        state: absent
