---
- import_playbook: obtain_session_token.yaml

- hosts: aws_sns_topic
  gather_facts: False
  tasks:
    - name: "sns_topic"
      sns_topic:
        name: "{{ aws_resource_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"

- hosts: aws_sqs_queue
  gather_facts: False
  tasks:
    - name: "sqs_queue"
      sqs_queue:
        name: "{{ aws_resource_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"

- hosts: aws_s3_bucket
  gather_facts: False
  tasks:
    - name: "s3_bucket"
      s3_bucket:
        name: "{{ aws_resource_name }}"
        state: absent
        force: true
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"

- hosts: aws_iam_user
  gather_facts: False
  tasks:
    - name: "iam_user"
      iam:
        iam_type: user
        name: "{{ aws_resource_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
    - name: "inventory/host_vars/aws_user/aws_user_creds.yaml"
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/aws_user_creds.yaml"
        state: absent
