---
- hosts: pdf_signer
  tasks:
    - name: "Deactivate Queue Reader Cron"
      cron:
        name: queue-reader.py
        state: absent
    - name: "Stop Queue Reader"
      command: pkill queue-reader.py
      register: result
      failed_when: false
      changed_when: "result.rc == 0"

- hosts: localhost
  tasks:
    - set_fact:
        docsigner_user_name: "{{ hostvars['docsigner_user']['name'] }}"
        pdf_store_bucket_name: "{{ hostvars['pdf_store_bucket']['name'] }}"
        transaction_signing_queue_name: "{{ hostvars['transaction_signing_queue']['name'] }}"
    - name: "Remove IAM Policies"
      iam_policy:
        iam_type: user
        iam_name: "{{ docsigner_user_name }}"
        policy_name: "{{ item }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items:
        - transaction_signing_queue_receiver
        - pdf_store_bucket_access
    - name: "Docsigner User"
      iam:
        iam_type: user
        name: "{{ docsigner_user_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - name: "PDF Store Bucket"
      s3_bucket:
        name: "{{ pdf_store_bucket_name }}"
        state: absent
        force: true
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - name: "Transaction Signing Queue"
      sqs_queue:
        name: "{{ transaction_signing_queue_name }}"
        state: absent
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
    - name: "inventory/aws-transaction_signing_queue"
      file:
        path: "{{ inventory_dir }}/aws-transaction_signing_queue"
        state: absent
    - name: "inventory/aws-pdf_store_bucket"
      file:
        path: "{{ inventory_dir }}/aws-pdf_store_bucket"
        state: absent
    - name: "inventory/aws-docsigner_user"
      file:
        path: "{{ inventory_dir }}/aws-docsigner_user"
        state: absent
