---
- import_playbook: obtain_session_token.yaml
- hosts: localhost
  tasks:
    - command: python "{{ playbook_dir }}/test-data/load-test-data.py"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
        AWS_SESSION_TOKEN: "{{ security_token }}"
        TRANSACTION_QUEUE: "{{ hostvars['transaction_signing_queue'].region }}:{{ hostvars['transaction_signing_queue'].name }}"
        PDF_BUCKET: "{{ hostvars['pdf_store_bucket'].region }}:{{ hostvars['pdf_store_bucket'].name }}:{{ hostvars['pdf_store_bucket'].s3_storage_class }}"
        SIGNING_EVENTS_TOPIC: "{{ hostvars['signing_events_topic'].region }}:{{ hostvars['signing_events_topic'].arn }}"
        PYTHONUNBUFFERED: true
