---
- hosts: pdf_signer
  tasks:
    - name: "Copy pdf-signer"
      synchronize:
        mode: pull
        src: "{{ ansible_user_dir }}/pdf-signer/"
        dest: "pdf-signer"
        perms: true
        recursive: true
        delete: true
        use_ssh_args: true
