---
# The prefix to add to all aws resources created for this environment
# typical values are dev / test / prod or similar
env_prefix: PREFIX

# A ULID that identifys this environment uniquely. This is used to
# ensure a unique name for resources that must be globally unique
# such as S3 bucket names
env_ulid: ULID

aws_region: SELECT_REGION

# The vault file containing the static aws access keys used to obtain a STS
# token using Multi-Factor Authentication
static_aws_key_vault: "{{ playbook_dir }}/vaults/{{ env_prefix }}-aws_creds.yaml"

gather_facts: false
ansible_connection: local
