---
name: "{{ env_prefix }}-{{ inventory_hostname }}-{{ env_ulid|lower }}"
region: "ap-southeast-2"
arn: "arn:aws:s3:::{{ name }}"

# The S3 storage class to use when uploading to S3. This is primarily to allow for
# REDUCED_REDUNDANCY for a minor cost saving in dev or other envs where data loss
# is not actually an issue
s3_storage_class: STANDARD
