---
- hosts: aws_control:!localhost
  tasks:
    - name: "Setup Temporary Credentials"
      set_fact:
        mfa_provided: "{{ hostvars['localhost'].mfa_provided }}"
        aws_access_key: "{{ hostvars['localhost'].aws_access_key }}"
        aws_secret_key: "{{ hostvars['localhost'].aws_secret_key }}"
        security_token: "{{ hostvars['localhost'].security_token }}"
        iam_aws_access_key: "{{ hostvars['localhost'].iam_aws_access_key }}"
        iam_aws_secret_key: "{{ hostvars['localhost'].iam_aws_secret_key }}"
        iam_security_token: "{{ hostvars['localhost'].iam_security_token|default(omit) }}"
      no_log: True
